### ISSUE TITLE
Caching Entry/User views kills logic for View Management (back to XX)

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#113]
Working on it now.

The issue is since the user/entry view is created, another view management event isn't added when you focus on something again, so we gotta figure out the logic.

**Comment by willhoney7** [comment]
Closing. If you see any issues, please re-open

**Comment by funkatron** [comment]
this should be applied to the production branch, not master, and then ported to master. Since it looks like you already committed and pushed it to master, you'll probably need to apply the changes manually to production.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by willhoney7** [comment]
But the bug is only in the merged pull request by @dcousineau?

**Comment by funkatron** [comment]
Actually I misunderstood your question. Talk to you on IRC.

---

It was merged before your push

**Comment by funkatron** [comment]
Sounds like this is only in master, so closing again. sorry for the false alarm!
