### ISSUE TITLE
About popup content seems to be too big

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#144]
Only shows up on device, so double check there before any changes. (don't have screenshot handy)

**Comment by nguarracino** [comment]
This seems to be caused by setting the z-index on the background image. The popup draws ok for a second or two, but when the scrim darkens the screen, a border appears on the right and bottom edges of the popup. Seems like it must be an Enyo or WebKit bug. It works fine without z-index, so I'm removing it.

**Comment by funkatron** [comment]
awesome, thanks!
