### ISSUE TITLE
Column: How to load older messages (UI)

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#25]
I'd go initially for a button at the bottom of the entries. Not sure how gestures will work out.

**Comment by nguarracino** [comment]
I see that we're using a VirtualRepeater for the columns. What about using a VirtualList instead? Then we could use the onAcquirePage event to fetch older messages without a dedicated button (if we decide that would be better than a button, anyway.)

**Comment by willhoney7** [comment]
We are currently using a VirtualRepeater because I was having issues with the list disappearing after calling ".render()". I couldn't narrow down a fix and so I gave up until later. I think a VirtualList would fit better.

If you can get it working, the specific test case is creating the entryView (which re-renders everything), that'd be great!

**Comment by funkatron** [comment]
Yeah, feel free to branch and give it a go.

**Comment by willhoney7** [comment]
@nguarracino added in the VirtualList so the UI for this is done..
