### ISSUE TITLE
Bind scroll events from mouse

### ISSUE THREAD

**Issue by paddycarver** [spazproject/Spaz-Enyo#51]
It would be pretty awesome if we could get the mouse scroll events to scroll columns.

**Comment by funkatron** [comment]
Yeah, I would love this. I suspect it might come in an Enyo update, but we may be able to find a workaround sooner.

**Comment by dcousineau** [comment]
If we do it ourselves, we may want to examine https://github.com/cubiq/iscroll and determine exactly how they achieve this, and/or suggest the Enyo team do the same.

Investigation lead to easily using jQuery and binding a "mousewheel" event (it's definitely doing some cross-browser refining in the background). As to whether Enyo propagates this event, etc, I have no clue as of yet.

**Comment by funkatron** [comment]
I actually got mousescroll working. Here's the problem: it doesn't trigger either the top ceiling of the column, or rendering elements outside of the current viewport. So you can scroll up past the apparent top of the column, and you can't see anything much beyond the currently rendered rows. Presumably this is because it's actually drag and flick gestures which drive the list.

I think we need to ask the Enyo folks themselves about this.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by dcousineau** [comment]
Well technically we got this a long while back
