### ISSUE TITLE
Use new Enyo 0.10 APIs to force keyboard open in the compose popup.

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#93]
Currently, the vkb is super annoying with the posting popup since it opens and closes.

I can't do this at the moment because I don't have the sdk installed to test it. If someone else can, that'd be great.

Assigning this to Nick, but he is free to change the assignment to whomever he wants.

**Comment by funkatron** [comment]
Agreed, very annoyingEd Finkler@funkatronFunkatron.comSent from my Palm PreOn Jun 1, 2011 5:43 PM, Tibfib reply@reply.github.com wrote: Currently, the vkb is super annoying with the posting popup since it opens and closes.
I can't do this at the moment because I don't have the sdk installed to test it. If someone else can, that'd be great.

## Assigning this to Nick, but he is free to change the assignment to whomever he wants.

Reply to this email directly or view it on GitHub:
https://github.com/funkatron/Spaz-Enyo/issues/93

**Comment by nguarracino** [comment]
We can definitely use the keyboard APIs to keep the keyboard open while the ComposePoup is shown.

The other issue is something about how our Popups are constructed, or maybe where they fit in the component hierarchy. They aren't being repositioned when the keyboard is shown. If you look at some of the example Popup apps in Chrome, the Popups will get repositioned when the browser is resized, which doesn't happen with the Spaz Popups.

**Comment by funkatron** [comment]
umm, I think I did this stuff. e549b93e476b04f03b7030eac34100287723f256 259b28573083d1a0906ecb0174e426a2d94f2e7b
