### ISSUE TITLE
Implement sharing actions

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#96]
Sharing actions:
- Email
- SMS/IM
- Copy Entry content to clipboard

Much of this can be pulled from the Mojo version and massaged for Enyo.

**Comment by funkatron** [comment]
Need to move on this. we will probably be submitting within 7 days.

**Comment by funkatron** [comment]
Also, we should implement sharing in the EntryView panel, and that panel's share button should include RTing and the above.

**Comment by nguarracino** [comment]
Sorry I've been MIA for a bit... gonna put some time in on this tonight.

**Comment by funkatron** [comment]
This is looking awesome!

**Comment by nguarracino** [comment]
Thanks! I think sharing should be in good shape at this point. The only thing that's bugging me is, I had trouble extending the existing PopupSelect to have a submenu, and to dynamically add entries for favorite/unfavorite when appropriate. So I switched over to a Menu - which works, but now I'm seeing that bug where the menu can be drawn partially offscreen again. Not sure if that's something we're doing wrong or an Enyo issue.

**Comment by funkatron** [comment]
This sounds like a really good thing for dcousineau to ask the engs at Palm.

**Comment by nguarracino** [comment]
So, after playing with this a bit more there are basically two questions I have:

We need to build up the Menu dynamically since not all items will always be there, depending on what you've tapped on. We are using the onBeforeOpen event to do this. One of the items we add is a submenu (the Share submenu.) There is a flicker as the menu is drawn - it looks like it momentarily draws to the full width, including the Share submenu as if it were open. Then it realizes the Share submenu is closed and redraws to the smaller size. Can we eliminate this flicker?

If you tap near the edge of the screen, the Menu is positioned so it's fully onscreen. However if you tap the Share submenu, it can be clipped by the edge of the screen. Is there a way for the Menu to try to reposition itself so the Share submenu is fully visible when it's opened?

@dcousineau - would you be able to pass those questions on to the powers that be?

**Comment by dcousineau** [comment]
Will do

**Comment by funkatron** [comment]
Did we get feedback on this?

**Comment by funkatron** [comment]
ping?

**Comment by dcousineau** [comment]
I wouldn't call it a brush off, but I brought it up a couple times with a couple guys.

**Comment by funkatron** [comment]
and they were like "uhhhh, look at that!"

**Comment by dcousineau** [comment]
Pretty much :P Actually one or two things got a "huh, that is broken isn't it" (namely the hack I had to eventually do with classname for the horizontal scroller to properly obey flex)

**Comment by funkatron** [comment]
Feel free to push hard with this via email to Adela. They want us to be ready for launch, so they need to help us out.

**Comment by willhoney7** [comment]
Another bug I noticed is that once you close the share drawer, you can no longer scroll. This is an issue when you are scrolled near the bottom and so you can't access the reply/repost/etc. commands unless you open the drawer again, scroll up, and close it.

**Comment by funkatron** [comment]
Since I've gotten no feedback on these things, I'm assuming they are "okay enough for launch," and I'm closing this.

File each issue you find _individually_, and label & place in the appropriate milestone.
